USE QuanLyHocVu	
GO

--11--
ALTER TABLE HOCVIEN
ADD CONSTRAINT chk_tuoi CHECK (YEAR(GETDATE()) - YEAR(NGSINH) >= 18)

--12--
ALTER TABLE GIANGDAY
ADD CONSTRAINT chk_ngay CHECK (TUNGAY < DENNGAY)

--13--
ALTER TABLE GIAOVIEN
ADD CONSTRAINT chk_tuoilam CHECK (YEAR(GETDATE()) - YEAR(NGSINH) >= 22)

--14--
ALTER TABLE MONHOC
ADD CONSTRAINT chk_tc CHECK (ABS(TCLT - TCTH) <= 3)