USE QuanLyHocVu
GO

--1--
SELECT HOCVIEN.MAHV, HOCVIEN.HO,HOCVIEN.TEN,LOP.MALOP
FROM HOCVIEN,LOP
WHERE LOP.TRGLOP = HOCVIEN.MAHV

--2--
SELECT HOCVIEN.MAHV, HOCVIEN.HO, HOCVIEN.TEN, KETQUATHI.LANTHI, KETQUATHI.DIEM
FROM KETQUATHI
JOIN HOCVIEN ON KETQUATHI.MAHV = HOCVIEN.MAHV
JOIN MONHOC ON KETQUATHI.MAMH = MONHOC.MAMH
WHERE MONHOC.TENMH = 'Cau truc roi rac'
  AND HOCVIEN.MALOP = 'K12'
ORDER BY HOCVIEN.HO ASC, HOCVIEN.TEN ASC

--3--
SELECT	HOCVIEN.MAHV,HO,TEN, MONHOC.MAMH,MONHOC.TENMH
FROM HOCVIEN
JOIN KETQUATHI ON HOCVIEN.MAHV = KETQUATHI.MAHV
JOIN MONHOC ON KETQUATHI.MAMH = MONHOC.MAMH
WHERE LANTHI < 2 AND KETQUATHI.KQUA = 'Dat'

--4--
SELECT	HOCVIEN.MAHV,HO,TEN, KETQUATHI.MAMH
FROM HOCVIEN
JOIN KETQUATHI ON HOCVIEN.MAHV = KETQUATHI.MAHV
JOIN MONHOC ON KETQUATHI.MAMH = MONHOC.MAMH
WHERE HOCVIEN.MALOP = 'K11' AND KETQUATHI.KQUA = 'Khong dat' AND LANTHI < 2 AND KETQUATHI.MAMH = 'CTRR'

--5--
SELECT DISTINCT HOCVIEN.MAHV, HOCVIEN.HO,HOCVIEN.TEN
FROM KETQUATHI
JOIN HOCVIEN ON KETQUATHI.MAHV = HOCVIEN.MAHV
JOIN MONHOC ON KETQUATHI.MAMH = MONHOC.MAMH
WHERE HOCVIEN.MALOP LIKE 'K%'
  AND KETQUATHI.MAMH = 'CTRR'
  AND KETQUATHI.KQUA = 'Khong Dat';